In [20]:
import requests
import pandas as pd
import config   ## File with API key
api_key = config.bea_key

# Components of request
base = 'https://www.bea.gov/api/data/?&UserID={}'.format(api_key)
m = '&method=GetData'
dsn = '&datasetname=NIPA'
ind = '&TableId=2'
freq = '&Frequency=Q'
year = '&Year=LAST12'
fmt = '&ResultFormat=json'

# Combined url for request
url = '{}{}{}{}{}{}{}'.format(base, m, dsn, ind, freq, year, fmt)
r = requests.get(url).json()
df = pd.DataFrame(r['BEAAPI']['Results']['Data'])
df['date'] = pd.to_datetime(df['TimePeriod'])
codes = ['A191RL', 'DPCERY', 'A006RY', 'A019RY', 'A822RY']
ind = ['date', 'SeriesCode']
df = df[df['SeriesCode'].isin(codes)].set_index(ind)['DataValue'].unstack(1)
df.to_csv('data/gdp_comp.csv')

# Record strings for later use in chart label
date = '{} Q{}'.format(df.index[-1].year, df.index[-1].quarter)
ch = df['A191RL'][-1]  # GDP in growth
label = '{}: Real GDP: {}T; Growth: {}\%'.format(date, Y, ch)

write_txt('gdp_comp.txt', label) # Write chart label to txt

In [24]:
import requests
import pandas as pd
import config   ## File with API key

def write_txt(filename, filetext):
# Write label to txt file
    with open(filename, 'w') as text_file:
        text_file.write(filetext)

# Components of request
base = 'https://www.bea.gov/api/data/?&UserID={}&method=GetData'.format(config.bea_key)
url = '{}&datasetname={}&TableId={}&Frequency={}&Year={}&ResultFormat=json'.format(
    base, 'NIPA', 2, 'Q', 'LAST12')    # Adjust here as needed
df = pd.DataFrame(requests.get(url).json()['BEAAPI']['Results']['Data'])
df['date'] = pd.to_datetime(df['TimePeriod'])
codes = ['A191RL', 'DPCERY', 'A006RY', 'A019RY', 'A822RY']
df = df[df['SeriesCode'].isin(codes)].set_index(['date', 'SeriesCode'])['DataValue'].unstack(1)
df.to_csv('data/gdp_comp.csv')

# GDP in levels latest value
url = '{}&datasetname={}&TableId={}&Frequency={}&Year={}&ResultFormat=json'.format(
    base, 'NIPA', 6, 'Q', 'LAST1')    # Adjust here as needed
Y = pd.DataFrame(requests.get(url).json()['BEAAPI']['Results']['Data'])['DataValue'][0]

# Record strings for later use in chart label
date = '{} Q{}'.format(df.index[-1].year, df.index[-1].quarter)
ch = df['A191RL'][-1]  # GDP in growth
label = '{}: Real GDP: {}T; Growth: {}\%'.format(date, round(float(Y.replace(',', ''))/1000,1), ch)

write_txt('data/gdp_comp.txt', label) # Write chart label to txt

In [14]:
url = '{}&datasetname={}&TableId={}&Frequency={}&Year={}&ResultFormat=json'.format(
    base, 'NIPA', 6, 'Q', 'LAST1')    # Adjust here as needed
Y = pd.DataFrame(requests.get(url).json()['BEAAPI']['Results']['Data'])['DataValue'][0]

In [21]:
v

u'16,842.4'

In [ ]:
# Combined url for request
url = '{}&datasetname={}&TableId={}&Frequency={}&Year=LAST12{}&ResultFormat=json'.format(
    base, 'NIPA', 2, 'Q', 'LAST12')

In [21]:
df.to_csv('data/test.csv')

In [17]:
df['date'] = pd.to_datetime(df['TimePeriod'])

In [18]:
codes = ['A191RL', 'DPCERY', 'A006RY', 'A019RY', 'A822RY']
df = df[df['SeriesCode'].isin(codes)].set_index(['date', 'SeriesCode'])['DataValue'].unstack(1)

SeriesCode A006RY A019RY A191RL A822RY DPCERY
date
2006-01-01   1.10   0.18    4.9   0.61   3.01
2006-04-01  -0.51   0.02    1.2   0.27   1.41
2006-07-01  -0.80  -0.57    0.4   0.16   1.56
2006-10-01  -1.83   1.74    3.2   0.51   2.75
2007-01-01  -0.71  -0.31    0.2  -0.16   1.43
2007-04-01   1.02   0.48    3.1   0.66   0.93
2007-07-01  -0.44   1.39    2.7   0.56   1.21
2007-10-01  -1.44   2.22    1.4   0.31   0.34
2008-01-01  -2.36  -0.11   -2.7   0.32  -0.56
2008-04-01  -1.21   2.11    2.0   0.62   0.48
2008-07-01  -1.86   0.77   -1.9   1.13  -1.94
2008-10-01  -5.74   0.15   -8.2   0.56  -3.16
2009-01-01  -7.02   2.30   -5.4   0.15  -0.86
2009-04-01  -3.25   2.34   -0.5   1.56  -1.19
2009-07-01  -0.40  -0.45    1.3   0.48   1.68
2009-10-01   4.05   0.06    3.9  -0.17  -0.01
2010-01-01   1.77  -0.85    1.7  -0.63   1.46
2010-04-01   2.86  -1.77    3.9   0.61   2.23
2010-07-01   1.86  -0.83    2.7  -0.07   1.77
2010-10-01  -0.51   1.12    2.5  -0.87   2.79
2011-01-01  -1.07  -0.24   -1.5  -1.60   1.38
2011-04-01   2.14   0.31    2.9  -0.08   0.57
2011-07-01   0.15   0.01    0.8  -0.52   1.20
2011-10-01   4.16  -0.21    4.6  -0.31   0.94
2012-01-01   1.47  -0.02    2.7  -0.40   1.63
2012-04-01   1.53   0.28    1.9  -0.39   0.45
2012-07-01  -0.18   0.16    0.5  -0.22   0.72
2012-10-01  -0.51   0.58    0.1  -0.75   0.78
2013-01-01   2.04   0.30    2.8  -0.83   1.32
2013-04-01   0.78  -0.21    0.8  -0.37   0.58
2013-07-01   2.08   0.13    3.1  -0.37   1.28
2013-10-01   0.91   1.29    4.0  -0.53   2.29
2014-01-01  -1.10  -1.16   -1.2  -0.19   1.26
2014-04-01   1.79  -0.41    4.0   0.02   2.56
2014-07-01   1.49   0.50    5.0   0.46   2.52
2014-10-01   0.45  -1.14    2.3  -0.07   3.07
2015-01-01   1.62  -1.65    2.0   0.45   1.63
2015-04-01   0.18  -0.08    2.6   0.57   1.94
2015-07-01   0.35  -0.52    2.0   0.34   1.81
2015-10-01  -0.39  -0.45    0.9   0.18   1.53
2016-01-01  -0.56   0.01    0.8   0.28   1.11
2016-04-01  -1.34   0.18    1.4  -0.30   2.88
2016-07-01   0.50   0.85    3.5   0.14   2.03
2016-10-01   1.47  -1.82    2.1   0.03   2.40
2017-01-01   0.69   0.07    0.7  -0.30   0.23